#!/usr/bin/env python3
"""Generate a lightweight TypeScript client from the FastAPI OpenAPI schema."""

from __future__ import annotations

import json
import re
from pathlib import Path

from finops_mcp.app import app


def _method_name(http_method: str, path: str) -> str:
    parts = [http_method.lower()]
    for token in path.strip("/").split("/"):
        token = token.strip()
        if not token:
            continue
        if token.startswith("{") and token.endswith("}"):
            token = f"by_{token[1:-1]}"
        token = re.sub(r"[^a-zA-Z0-9_]", "_", token)
        parts.append(token.lower())
    raw = "_".join(parts)
    return re.sub(r"_+", "_", raw).strip("_")


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    generated_dir = root / "dashboard" / "lib" / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)

    schema = app.openapi()
    openapi_json_path = generated_dir / "openapi.json"
    openapi_json_path.write_text(json.dumps(schema, indent=2), encoding="utf-8")

    lines: list[str] = []
    lines.append("// Auto-generated by scripts/generate_openapi_client.py")
    lines.append("// Do not edit manually.")
    lines.append("")
    lines.append("export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'")
    lines.append("")
    lines.append("export interface ApiRequestOptions {")
    lines.append("  method: HttpMethod")
    lines.append("  path: string")
    lines.append("  query?: Record<string, string | number | boolean | undefined | null>")
    lines.append("  body?: unknown")
    lines.append("  headers?: HeadersInit")
    lines.append("}")
    lines.append("")
    lines.append("function withQuery(path: string, query?: ApiRequestOptions['query']): string {")
    lines.append("  if (!query) return path")
    lines.append("  const params = new URLSearchParams()")
    lines.append("  for (const [k, v] of Object.entries(query)) {")
    lines.append("    if (v !== undefined && v !== null) params.set(k, String(v))")
    lines.append("  }")
    lines.append("  const qs = params.toString()")
    lines.append("  return qs ? `${path}?${qs}` : path")
    lines.append("}")
    lines.append("")
    lines.append("export function createOpenApiClient(baseUrl: string, fetcher: typeof fetch = fetch) {")
    lines.append("  async function request<T = any>(options: ApiRequestOptions): Promise<T> {")
    lines.append("    const url = `${baseUrl}${withQuery(options.path, options.query)}`")
    lines.append("    const headers = new Headers(options.headers || {})")
    lines.append("    if (options.body !== undefined) headers.set('Content-Type', 'application/json')")
    lines.append("    const response = await fetcher(url, {")
    lines.append("      method: options.method,")
    lines.append("      headers,")
    lines.append("      body: options.body !== undefined ? JSON.stringify(options.body) : undefined,")
    lines.append("    })")
    lines.append("    if (!response.ok) throw new Error(await response.text())")
    lines.append("    const contentType = response.headers.get('content-type') || ''")
    lines.append("    if (contentType.includes('application/json')) return (await response.json()) as T")
    lines.append("    return (await response.text()) as T")
    lines.append("  }")

    paths = schema.get("paths", {})
    for path, methods in sorted(paths.items()):
        if not isinstance(methods, dict):
            continue
        for method, _operation in sorted(methods.items()):
            method_upper = str(method).upper()
            if method_upper not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            fn_name = _method_name(method_upper, path)
            lines.append("")
            lines.append(
                f"  async function {fn_name}(args: {{"
                " pathParams?: Record<string, string | number>; "
                "query?: Record<string, string | number | boolean | undefined | null>; "
                "body?: unknown; headers?: HeadersInit } = {}) {"
            )
            lines.append("    let resolvedPath = " + json.dumps(path))
            lines.append("    for (const [k, v] of Object.entries(args.pathParams || {})) {")
            lines.append("      resolvedPath = resolvedPath.replace(`{${k}}`, encodeURIComponent(String(v)))")
            lines.append("    }")
            lines.append("    return request({")
            lines.append(f"      method: '{method_upper}',")
            lines.append("      path: resolvedPath,")
            lines.append("      query: args.query,")
            lines.append("      body: args.body,")
            lines.append("      headers: args.headers,")
            lines.append("    })")
            lines.append("  }")

    lines.append("")
    lines.append("  return {")
    for path, methods in sorted(paths.items()):
        if not isinstance(methods, dict):
            continue
        for method, _operation in sorted(methods.items()):
            method_upper = str(method).upper()
            if method_upper not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            fn_name = _method_name(method_upper, path)
            lines.append(f"    {fn_name},")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    client_path = generated_dir / "openapi-client.ts"
    client_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {openapi_json_path}")
    print(f"Wrote {client_path}")


if __name__ == "__main__":
    main()
